
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Linux - 6.5.0-17-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /bin/clang++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is Clang, found in:
        /home/oldbuddy/Projects/thinning/cmake-build-debug/CMakeFiles/3.27.8/CompilerIdCXX/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "/home/oldbuddy/Projects/thinning/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-Kvks7m"
      binary: "/home/oldbuddy/Projects/thinning/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-Kvks7m"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/oldbuddy/Projects/thinning/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-Kvks7m'
        
        Run Build Command(s): /home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/ninja/linux/x64/ninja -v cmTC_04134
        [1/2] /bin/clang++   -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o -MF CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o.d -o CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o -c /home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeCXXCompilerABI.cpp
        Ubuntu clang version 14.0.0-1ubuntu1.1
        Target: x86_64-pc-linux-gnu
        Thread model: posix
        InstalledDir: /bin
        Found candidate GCC installation: /bin/../lib/gcc/x86_64-linux-gnu/11
        Found candidate GCC installation: /bin/../lib/gcc/x86_64-linux-gnu/12
        Selected GCC installation: /bin/../lib/gcc/x86_64-linux-gnu/12
        Candidate multilib: .;@m64
        Selected multilib: .;@m64
         (in-process)
         "/usr/lib/llvm-14/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCXXCompilerABI.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/oldbuddy/Projects/thinning/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-Kvks7m -resource-dir /usr/lib/llvm-14/lib/clang/14.0.0 -dependency-file CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o.d -MT CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o -sys-header-deps -internal-isystem /bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12 -internal-isystem /bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12 -internal-isystem /bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/backward -internal-isystem /usr/lib/llvm-14/lib/clang/14.0.0/include -internal-isystem /usr/local/include -internal-isystem /bin/../lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir=/home/oldbuddy/Projects/thinning/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-Kvks7m -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o -x c++ /home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeCXXCompilerABI.cpp
        clang -cc1 version 14.0.0 based upon LLVM 14.0.0 default target x86_64-pc-linux-gnu
        ignoring nonexistent directory "/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include"
        ignoring nonexistent directory "/include"
        #include "..." search starts here:
        #include <...> search starts here:
         /bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12
         /bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12
         /bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/backward
         /usr/lib/llvm-14/lib/clang/14.0.0/include
         /usr/local/include
         /usr/include/x86_64-linux-gnu
         /usr/include
        End of search list.
        [2/2] : && /bin/clang++  -v CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o -o cmTC_04134   && :
        Ubuntu clang version 14.0.0-1ubuntu1.1
        Target: x86_64-pc-linux-gnu
        Thread model: posix
        InstalledDir: /bin
        Found candidate GCC installation: /bin/../lib/gcc/x86_64-linux-gnu/11
        Found candidate GCC installation: /bin/../lib/gcc/x86_64-linux-gnu/12
        Selected GCC installation: /bin/../lib/gcc/x86_64-linux-gnu/12
        Candidate multilib: .;@m64
        Selected multilib: .;@m64
         "/bin/ld" -pie -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTC_04134 /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crti.o /bin/../lib/gcc/x86_64-linux-gnu/12/crtbeginS.o -L/bin/../lib/gcc/x86_64-linux-gnu/12 -L/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/usr/lib/llvm-14/bin/../lib -L/lib -L/usr/lib CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /bin/../lib/gcc/x86_64-linux-gnu/12/crtendS.o /lib/x86_64-linux-gnu/crtn.o
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:127 (message)"
      - "/home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Parsed CXX implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12]
          add: [/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12]
          add: [/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/backward]
          add: [/usr/lib/llvm-14/lib/clang/14.0.0/include]
          add: [/usr/local/include]
          add: [/usr/include/x86_64-linux-gnu]
          add: [/usr/include]
        end of search list found
        collapse include dir [/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12] ==> [/include/c++/12]
        collapse include dir [/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12] ==> [/include/x86_64-linux-gnu/c++/12]
        collapse include dir [/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/backward] ==> [/include/c++/12/backward]
        collapse include dir [/usr/lib/llvm-14/lib/clang/14.0.0/include] ==> [/usr/lib/llvm-14/lib/clang/14.0.0/include]
        collapse include dir [/usr/local/include] ==> [/usr/local/include]
        collapse include dir [/usr/include/x86_64-linux-gnu] ==> [/usr/include/x86_64-linux-gnu]
        collapse include dir [/usr/include] ==> [/usr/include]
        implicit include dirs: [/include/c++/12;/include/x86_64-linux-gnu/c++/12;/include/c++/12/backward;/usr/lib/llvm-14/lib/clang/14.0.0/include;/usr/local/include;/usr/include/x86_64-linux-gnu;/usr/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:152 (message)"
      - "/home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        ignore line: [Change Dir: '/home/oldbuddy/Projects/thinning/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-Kvks7m']
        ignore line: []
        ignore line: [Run Build Command(s): /home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/ninja/linux/x64/ninja -v cmTC_04134]
        ignore line: [[1/2] /bin/clang++   -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o -MF CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o.d -o CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o -c /home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeCXXCompilerABI.cpp]
        ignore line: [Ubuntu clang version 14.0.0-1ubuntu1.1]
        ignore line: [Target: x86_64-pc-linux-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /bin]
        ignore line: [Found candidate GCC installation: /bin/../lib/gcc/x86_64-linux-gnu/11]
        ignore line: [Found candidate GCC installation: /bin/../lib/gcc/x86_64-linux-gnu/12]
        ignore line: [Selected GCC installation: /bin/../lib/gcc/x86_64-linux-gnu/12]
        ignore line: [Candidate multilib: .]
        ignore line: [@m64]
        ignore line: [Selected multilib: .]
        ignore line: [@m64]
        ignore line: [ (in-process)]
        ignore line: [ "/usr/lib/llvm-14/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCXXCompilerABI.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/oldbuddy/Projects/thinning/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-Kvks7m -resource-dir /usr/lib/llvm-14/lib/clang/14.0.0 -dependency-file CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o.d -MT CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o -sys-header-deps -internal-isystem /bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12 -internal-isystem /bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12 -internal-isystem /bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/backward -internal-isystem /usr/lib/llvm-14/lib/clang/14.0.0/include -internal-isystem /usr/local/include -internal-isystem /bin/../lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir=/home/oldbuddy/Projects/thinning/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-Kvks7m -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o -x c++ /home/oldbuddy/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeCXXCompilerABI.cpp]
        ignore line: [clang -cc1 version 14.0.0 based upon LLVM 14.0.0 default target x86_64-pc-linux-gnu]
        ignore line: [ignoring nonexistent directory "/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include"]
        ignore line: [ignoring nonexistent directory "/include"]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12]
        ignore line: [ /bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12]
        ignore line: [ /bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/backward]
        ignore line: [ /usr/lib/llvm-14/lib/clang/14.0.0/include]
        ignore line: [ /usr/local/include]
        ignore line: [ /usr/include/x86_64-linux-gnu]
        ignore line: [ /usr/include]
        ignore line: [End of search list.]
        ignore line: [[2/2] : && /bin/clang++  -v CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o -o cmTC_04134   && :]
        ignore line: [Ubuntu clang version 14.0.0-1ubuntu1.1]
        ignore line: [Target: x86_64-pc-linux-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /bin]
        ignore line: [Found candidate GCC installation: /bin/../lib/gcc/x86_64-linux-gnu/11]
        ignore line: [Found candidate GCC installation: /bin/../lib/gcc/x86_64-linux-gnu/12]
        ignore line: [Selected GCC installation: /bin/../lib/gcc/x86_64-linux-gnu/12]
        ignore line: [Candidate multilib: .]
        ignore line: [@m64]
        ignore line: [Selected multilib: .]
        ignore line: [@m64]
        link line: [ "/bin/ld" -pie -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTC_04134 /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crti.o /bin/../lib/gcc/x86_64-linux-gnu/12/crtbeginS.o -L/bin/../lib/gcc/x86_64-linux-gnu/12 -L/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/usr/lib/llvm-14/bin/../lib -L/lib -L/usr/lib CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /bin/../lib/gcc/x86_64-linux-gnu/12/crtendS.o /lib/x86_64-linux-gnu/crtn.o]
          arg [/bin/ld] ==> ignore
          arg [-pie] ==> ignore
          arg [-zrelro] ==> ignore
          arg [--hash-style=gnu] ==> ignore
          arg [--build-id] ==> ignore
          arg [--eh-frame-hdr] ==> ignore
          arg [-m] ==> ignore
          arg [elf_x86_64] ==> ignore
          arg [-dynamic-linker] ==> ignore
          arg [/lib64/ld-linux-x86-64.so.2] ==> ignore
          arg [-o] ==> ignore
          arg [cmTC_04134] ==> ignore
          arg [/lib/x86_64-linux-gnu/Scrt1.o] ==> obj [/lib/x86_64-linux-gnu/Scrt1.o]
          arg [/lib/x86_64-linux-gnu/crti.o] ==> obj [/lib/x86_64-linux-gnu/crti.o]
          arg [/bin/../lib/gcc/x86_64-linux-gnu/12/crtbeginS.o] ==> obj [/bin/../lib/gcc/x86_64-linux-gnu/12/crtbeginS.o]
          arg [-L/bin/../lib/gcc/x86_64-linux-gnu/12] ==> dir [/bin/../lib/gcc/x86_64-linux-gnu/12]
          arg [-L/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../lib64] ==> dir [/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../lib64]
          arg [-L/lib/x86_64-linux-gnu] ==> dir [/lib/x86_64-linux-gnu]
          arg [-L/lib/../lib64] ==> dir [/lib/../lib64]
          arg [-L/usr/lib/x86_64-linux-gnu] ==> dir [/usr/lib/x86_64-linux-gnu]
          arg [-L/usr/lib/../lib64] ==> dir [/usr/lib/../lib64]
          arg [-L/usr/lib/llvm-14/bin/../lib] ==> dir [/usr/lib/llvm-14/bin/../lib]
          arg [-L/lib] ==> dir [/lib]
          arg [-L/usr/lib] ==> dir [/usr/lib]
          arg [CMakeFiles/cmTC_04134.dir/CMakeCXXCompilerABI.cpp.o] ==> ignore
          arg [-lstdc++] ==> lib [stdc++]
          arg [-lm] ==> lib [m]
          arg [-lgcc_s] ==> lib [gcc_s]
          arg [-lgcc] ==> lib [gcc]
          arg [-lc] ==> lib [c]
          arg [-lgcc_s] ==> lib [gcc_s]
          arg [-lgcc] ==> lib [gcc]
          arg [/bin/../lib/gcc/x86_64-linux-gnu/12/crtendS.o] ==> obj [/bin/../lib/gcc/x86_64-linux-gnu/12/crtendS.o]
          arg [/lib/x86_64-linux-gnu/crtn.o] ==> obj [/lib/x86_64-linux-gnu/crtn.o]
        collapse obj [/bin/../lib/gcc/x86_64-linux-gnu/12/crtbeginS.o] ==> [/lib/gcc/x86_64-linux-gnu/12/crtbeginS.o]
        collapse obj [/bin/../lib/gcc/x86_64-linux-gnu/12/crtendS.o] ==> [/lib/gcc/x86_64-linux-gnu/12/crtendS.o]
        collapse library dir [/bin/../lib/gcc/x86_64-linux-gnu/12] ==> [/lib/gcc/x86_64-linux-gnu/12]
        collapse library dir [/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../lib64] ==> [/lib64]
        collapse library dir [/lib/x86_64-linux-gnu] ==> [/lib/x86_64-linux-gnu]
        collapse library dir [/lib/../lib64] ==> [/lib64]
        collapse library dir [/usr/lib/x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
        collapse library dir [/usr/lib/../lib64] ==> [/usr/lib64]
        collapse library dir [/usr/lib/llvm-14/bin/../lib] ==> [/usr/lib/llvm-14/lib]
        collapse library dir [/lib] ==> [/lib]
        collapse library dir [/usr/lib] ==> [/usr/lib]
        implicit libs: [stdc++;m;gcc_s;gcc;c;gcc_s;gcc]
        implicit objs: [/lib/x86_64-linux-gnu/Scrt1.o;/lib/x86_64-linux-gnu/crti.o;/lib/gcc/x86_64-linux-gnu/12/crtbeginS.o;/lib/gcc/x86_64-linux-gnu/12/crtendS.o;/lib/x86_64-linux-gnu/crtn.o]
        implicit dirs: [/lib/gcc/x86_64-linux-gnu/12;/lib64;/lib/x86_64-linux-gnu;/usr/lib/x86_64-linux-gnu;/usr/lib64;/usr/lib/llvm-14/lib;/lib;/usr/lib]
        implicit fwks: []
      
      
...
